spring:
  datasource:
    url: jdbc:mariadb://localhost/sample
    driverClassName: org.mariadb.jdbc.Driver
    username: sa
    password: password

  mvc:
    hiddenmethod:
      filter:
        enabled: true
