version: "3"
services:
  db:
    build: db
    image: db:0.0.1
    restart: always
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rpassword
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d

volumes:
  maria-db:
    driver: local
